#!/usr/bin/env python3
"""embed_file.py <input> <output.h> <symbol> — byte-array embed for build-time
resources (the GUI HTML). Hex array rather than a raw string literal so the
content can never collide with a delimiter or hit MSVC's string-length cap."""
import sys

src, dst, sym = sys.argv[1], sys.argv[2], sys.argv[3]
data = open(src, "rb").read()
with open(dst, "w") as f:
    f.write("// generated by tools/embed_file.py — do not edit\n#pragma once\n#include <cstddef>\n")
    f.write(f"static const unsigned char {sym}_data[] = {{\n")
    for i in range(0, len(data), 24):
        f.write("  " + ",".join(str(b) for b in data[i:i + 24]) + ",\n")
    f.write("};\n")
    f.write(f"static const size_t {sym}_size = {len(data)};\n")
