import re

# 1. emit the graph as a C++ header the shell can consult, generated from the
#    same table the GUI reads -- one declaration, two consumers.
rows = [l.split('\t') for l in open('src/param_presentation.tsv').read().split('\n')
        if l and not l.startswith('#')]
hdr = rows[0]
di = hdr.index('depends')
ai = hdr.index('address')

# address -> depends clause, only for rows that declare one
deps = {}
for r in rows[1:]:
    if len(r) > di and r[di].strip() and r[di].strip() != 'never':
        deps[r[ai]] = r[di].strip()

# resolve addresses to ids using the shell's own param table
src = open('src/hypersaw_clap.cpp').read()
ids = {}
for m in re.finditer(r'\{(\d+), "([A-Za-z0-9_]+)"', src):
    ids[m.group(2)] = int(m.group(1))

STRIDE = 1000
out = []
for addr, clause in sorted(deps.items()):
    if '.' in addr:
        osc, base = addr.split('.', 1)
        k = int(osc.replace('osc', '')) - 1
    else:
        base, k = addr, 0
    if base not in ids:
        continue
    pid = ids[base] + k * STRIDE
    # each clause: groups by ';', ANDs by ',', values by '|'
    groups = []
    for grp in clause.split(';'):
        conds = []
        for cl in grp.split(','):
            if '=' not in cl:
                continue
            key, vals = cl.split('=', 1)
            if key not in ids:
                continue
            kid = ids[key] + k * STRIDE if not key.startswith('osc') else ids[key]
            for v in vals.split('|'):
                try:
                    conds.append((kid, float(v)))
                except ValueError:
                    pass
        if conds:
            groups.append(conds)
    if groups:
        out.append((pid, groups))

hdr_txt = ['// GENERATED by tools/gen_depends_header.py -- do not edit.',
           '// The feature-dependency graph as the ENGINE sees it (ADR-108).',
           '// Same declaration the GUI derives shown_when from, so the morph',
           '// hierarchy and the visibility can never disagree about whether a',
           '// parameter is live.',
           '#pragma once',
           '#include <cstdint>',
           'namespace hypersaw {',
           'struct DepCond { uint32_t id; double value; };',
           'struct DepRule { uint32_t id; const DepCond *conds; int nConds; };',
           '// A parameter is LIVE when any of its conditions holds (values within a',
           '// clause are alternatives). Conservative by design: a rule we cannot',
           '// resolve is simply absent, and an absent rule means always-live.']
body, table = [], []
for pid, groups in out:
    flat = [c for g in groups for c in g]
    name = f'kDep{pid}'
    body.append('static const DepCond %s[] = {%s};' %
                (name, ', '.join('{%d, %g}' % (i, v) for i, v in flat)))
    table.append('  {%d, %s, %d},' % (pid, name, len(flat)))
hdr_txt += body
hdr_txt.append('static const DepRule kDepRules[] = {')
hdr_txt += table
hdr_txt.append('};')
hdr_txt.append('static const int kNumDepRules = %d;' % len(table))
hdr_txt.append('}  // namespace hypersaw')
open('src/depends_graph.h', 'w').write('\n'.join(hdr_txt) + '\n')
print("depends_graph.h:", len(table), "rules")
