// GENERATED by tools/gen_depends_header.py -- do not edit.
// The feature-dependency graph as the ENGINE sees it (ADR-108).
// Same declaration the GUI derives shown_when from, so the morph
// hierarchy and the visibility can never disagree about whether a
// parameter is live.
#pragma once
#include <cstdint>
namespace hypersaw {
struct DepCond { uint32_t id; double value; };
struct DepRule { uint32_t id; const DepCond *conds; int nConds; };
// A parameter is LIVE when any of its conditions holds (values within a
// clause are alternatives). Conservative by design: a rule we cannot
// resolve is simply absent, and an absent rule means always-live.
static const DepCond kDep111[] = {{106, 4}};
static const DepCond kDep112[] = {{106, 4}};
static const DepCond kDep115[] = {{114, 1}, {114, 2}, {114, 3}, {114, 4}};
static const DepCond kDep147[] = {{146, 1}};
static const DepCond kDep146[] = {{114, 1}, {114, 2}, {114, 3}, {114, 4}};
static const DepCond kDep148[] = {{146, 2}};
static const DepCond kDep108[] = {{106, 2}};
static const DepCond kDep113[] = {{106, 1}, {106, 2}, {106, 3}, {106, 4}};
static const DepCond kDep110[] = {{106, 4}};
static const DepCond kDep109[] = {{106, 3}};
static const DepCond kDep107[] = {{106, 1}};
static const DepCond kDep203[] = {{57, 7}, {57, 8}};
static const DepCond kDep206[] = {{57, 7}, {57, 8}};
static const DepCond kDep204[] = {{57, 7}, {57, 8}};
static const DepCond kDep200[] = {{57, 7}, {57, 8}};
static const DepCond kDep201[] = {{57, 7}, {57, 8}};
static const DepCond kDep205[] = {{57, 7}, {57, 8}};
static const DepCond kDep202[] = {{57, 7}, {57, 8}};
static const DepCond kDep211[] = {{59, 7}, {59, 8}};
static const DepCond kDep214[] = {{59, 7}, {59, 8}};
static const DepCond kDep212[] = {{59, 7}, {59, 8}};
static const DepCond kDep208[] = {{59, 7}, {59, 8}};
static const DepCond kDep209[] = {{59, 7}, {59, 8}};
static const DepCond kDep213[] = {{59, 7}, {59, 8}};
static const DepCond kDep210[] = {{59, 7}, {59, 8}};
static const DepCond kDep219[] = {{61, 7}, {61, 8}};
static const DepCond kDep222[] = {{61, 7}, {61, 8}};
static const DepCond kDep220[] = {{61, 7}, {61, 8}};
static const DepCond kDep216[] = {{61, 7}, {61, 8}};
static const DepCond kDep217[] = {{61, 7}, {61, 8}};
static const DepCond kDep221[] = {{61, 7}, {61, 8}};
static const DepCond kDep218[] = {{61, 7}, {61, 8}};
static const DepCond kDep227[] = {{63, 7}, {63, 8}};
static const DepCond kDep230[] = {{63, 7}, {63, 8}};
static const DepCond kDep228[] = {{63, 7}, {63, 8}};
static const DepCond kDep224[] = {{63, 7}, {63, 8}};
static const DepCond kDep225[] = {{63, 7}, {63, 8}};
static const DepCond kDep229[] = {{63, 7}, {63, 8}};
static const DepCond kDep226[] = {{63, 7}, {63, 8}};
static const DepCond kDep33[] = {{137, 0}, {138, 3}};
static const DepCond kDep155[] = {{151, 1}};
static const DepCond kDep158[] = {{151, 1}};
static const DepCond kDep157[] = {{151, 1}};
static const DepCond kDep156[] = {{151, 1}};
static const DepCond kDep154[] = {{151, 1}};
static const DepCond kDep152[] = {{151, 1}};
static const DepCond kDep153[] = {{151, 1}};
static const DepCond kDep142[] = {{137, 0}, {138, 4}};
static const DepCond kDep143[] = {{137, 0}, {138, 4}};
static const DepCond kDep145[] = {{137, 0}, {144, 1}, {144, 2}};
static const DepCond kDep138[] = {{137, 0}};
static const DepCond kDep144[] = {{137, 0}};
static const DepCond kDep140[] = {{137, 0}, {138, 2}};
static const DepCond kDep141[] = {{137, 0}, {138, 4}};
static const DepCond kDep139[] = {{137, 0}, {138, 1}};
static const DepCond kDep56[] = {{24, 2}};
static const DepCond kDep23[] = {{5, 3}};
static const DepCond kDep79[] = {{5, 4}};
static const DepCond kDep26[] = {{24, 2}};
static const DepCond kDep28[] = {{24, 0}};
static const DepCond kDep25[] = {{24, 1}};
static const DepCond kDep80[] = {{5, 5}};
static const DepCond kDep1056[] = {{1024, 2}};
static const DepCond kDep1023[] = {{1005, 3}};
static const DepCond kDep1079[] = {{1005, 4}};
static const DepCond kDep1026[] = {{1024, 2}};
static const DepCond kDep1028[] = {{1024, 0}};
static const DepCond kDep1025[] = {{1024, 1}};
static const DepCond kDep1080[] = {{1005, 5}};
static const DepCond kDep117[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep118[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep127[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep128[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep119[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep120[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep121[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep122[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep123[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep124[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep125[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep126[] = {{114, 2}, {114, 3}, {114, 4}, {144, 2}};
static const DepCond kDep116[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepRule kDepRules[] = {
  {111, kDep111, 1},
  {112, kDep112, 1},
  {115, kDep115, 4},
  {147, kDep147, 1},
  {146, kDep146, 4},
  {148, kDep148, 1},
  {108, kDep108, 1},
  {113, kDep113, 4},
  {110, kDep110, 1},
  {109, kDep109, 1},
  {107, kDep107, 1},
  {203, kDep203, 2},
  {206, kDep206, 2},
  {204, kDep204, 2},
  {200, kDep200, 2},
  {201, kDep201, 2},
  {205, kDep205, 2},
  {202, kDep202, 2},
  {211, kDep211, 2},
  {214, kDep214, 2},
  {212, kDep212, 2},
  {208, kDep208, 2},
  {209, kDep209, 2},
  {213, kDep213, 2},
  {210, kDep210, 2},
  {219, kDep219, 2},
  {222, kDep222, 2},
  {220, kDep220, 2},
  {216, kDep216, 2},
  {217, kDep217, 2},
  {221, kDep221, 2},
  {218, kDep218, 2},
  {227, kDep227, 2},
  {230, kDep230, 2},
  {228, kDep228, 2},
  {224, kDep224, 2},
  {225, kDep225, 2},
  {229, kDep229, 2},
  {226, kDep226, 2},
  {33, kDep33, 2},
  {155, kDep155, 1},
  {158, kDep158, 1},
  {157, kDep157, 1},
  {156, kDep156, 1},
  {154, kDep154, 1},
  {152, kDep152, 1},
  {153, kDep153, 1},
  {142, kDep142, 2},
  {143, kDep143, 2},
  {145, kDep145, 3},
  {138, kDep138, 1},
  {144, kDep144, 1},
  {140, kDep140, 2},
  {141, kDep141, 2},
  {139, kDep139, 2},
  {56, kDep56, 1},
  {23, kDep23, 1},
  {79, kDep79, 1},
  {26, kDep26, 1},
  {28, kDep28, 1},
  {25, kDep25, 1},
  {80, kDep80, 1},
  {1056, kDep1056, 1},
  {1023, kDep1023, 1},
  {1079, kDep1079, 1},
  {1026, kDep1026, 1},
  {1028, kDep1028, 1},
  {1025, kDep1025, 1},
  {1080, kDep1080, 1},
  {117, kDep117, 4},
  {118, kDep118, 4},
  {127, kDep127, 4},
  {128, kDep128, 4},
  {119, kDep119, 4},
  {120, kDep120, 4},
  {121, kDep121, 4},
  {122, kDep122, 4},
  {123, kDep123, 4},
  {124, kDep124, 4},
  {125, kDep125, 4},
  {126, kDep126, 4},
  {116, kDep116, 3},
};
static const int kNumDepRules = 82;
}  // namespace hypersaw
