// GENERATED by tools/gen_depends_header.py -- do not edit.
// The feature-dependency graph as the ENGINE sees it (ADR-108).
// Same declaration the GUI derives shown_when from, so the morph
// hierarchy and the visibility can never disagree about whether a
// parameter is live.
#pragma once
#include <cstdint>
namespace hypersaw {
struct DepCond { uint32_t id; double value; };
struct DepRule { uint32_t id; const DepCond *conds; int nConds; };
// A parameter is LIVE when any of its conditions holds (values within a
// clause are alternatives). Conservative by design: a rule we cannot
// resolve is simply absent, and an absent rule means always-live.
static const DepCond kDep111[] = {{106, 4}};
static const DepCond kDep112[] = {{106, 4}};
static const DepCond kDep115[] = {{114, 1}, {114, 2}, {114, 3}};
static const DepCond kDep147[] = {{146, 1}};
static const DepCond kDep146[] = {{114, 1}, {114, 2}, {114, 3}};
static const DepCond kDep148[] = {{146, 2}};
static const DepCond kDep108[] = {{106, 2}};
static const DepCond kDep113[] = {{106, 1}, {106, 2}, {106, 3}, {106, 4}};
static const DepCond kDep110[] = {{106, 4}};
static const DepCond kDep109[] = {{106, 3}};
static const DepCond kDep107[] = {{106, 1}};
static const DepCond kDep33[] = {{137, 0}, {138, 3}};
static const DepCond kDep155[] = {{151, 1}};
static const DepCond kDep158[] = {{151, 1}, {157, 0}};
static const DepCond kDep157[] = {{151, 1}};
static const DepCond kDep156[] = {{151, 1}};
static const DepCond kDep154[] = {{151, 1}};
static const DepCond kDep152[] = {{151, 1}};
static const DepCond kDep153[] = {{151, 1}};
static const DepCond kDep142[] = {{137, 0}, {138, 4}};
static const DepCond kDep143[] = {{137, 0}, {138, 4}};
static const DepCond kDep145[] = {{137, 0}, {144, 1}, {144, 2}};
static const DepCond kDep138[] = {{137, 0}};
static const DepCond kDep144[] = {{137, 0}};
static const DepCond kDep140[] = {{137, 0}, {138, 2}};
static const DepCond kDep141[] = {{137, 0}, {138, 4}};
static const DepCond kDep139[] = {{137, 0}, {138, 1}};
static const DepCond kDep56[] = {{24, 2}};
static const DepCond kDep23[] = {{5, 3}};
static const DepCond kDep79[] = {{5, 4}};
static const DepCond kDep26[] = {{24, 2}};
static const DepCond kDep28[] = {{24, 0}};
static const DepCond kDep25[] = {{24, 1}};
static const DepCond kDep80[] = {{5, 5}};
static const DepCond kDep1056[] = {{1024, 2}};
static const DepCond kDep1023[] = {{1005, 3}};
static const DepCond kDep1079[] = {{1005, 4}};
static const DepCond kDep1026[] = {{1024, 2}};
static const DepCond kDep1028[] = {{1024, 0}};
static const DepCond kDep1025[] = {{1024, 1}};
static const DepCond kDep1080[] = {{1005, 5}};
static const DepCond kDep117[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep118[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep127[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep128[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep119[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep120[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep121[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep122[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep123[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep124[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep125[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep126[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepCond kDep116[] = {{114, 2}, {114, 3}, {144, 2}};
static const DepRule kDepRules[] = {
  {111, kDep111, 1},
  {112, kDep112, 1},
  {115, kDep115, 3},
  {147, kDep147, 1},
  {146, kDep146, 3},
  {148, kDep148, 1},
  {108, kDep108, 1},
  {113, kDep113, 4},
  {110, kDep110, 1},
  {109, kDep109, 1},
  {107, kDep107, 1},
  {33, kDep33, 2},
  {155, kDep155, 1},
  {158, kDep158, 2},
  {157, kDep157, 1},
  {156, kDep156, 1},
  {154, kDep154, 1},
  {152, kDep152, 1},
  {153, kDep153, 1},
  {142, kDep142, 2},
  {143, kDep143, 2},
  {145, kDep145, 3},
  {138, kDep138, 1},
  {144, kDep144, 1},
  {140, kDep140, 2},
  {141, kDep141, 2},
  {139, kDep139, 2},
  {56, kDep56, 1},
  {23, kDep23, 1},
  {79, kDep79, 1},
  {26, kDep26, 1},
  {28, kDep28, 1},
  {25, kDep25, 1},
  {80, kDep80, 1},
  {1056, kDep1056, 1},
  {1023, kDep1023, 1},
  {1079, kDep1079, 1},
  {1026, kDep1026, 1},
  {1028, kDep1028, 1},
  {1025, kDep1025, 1},
  {1080, kDep1080, 1},
  {117, kDep117, 3},
  {118, kDep118, 3},
  {127, kDep127, 3},
  {128, kDep128, 3},
  {119, kDep119, 3},
  {120, kDep120, 3},
  {121, kDep121, 3},
  {122, kDep122, 3},
  {123, kDep123, 3},
  {124, kDep124, 3},
  {125, kDep125, 3},
  {126, kDep126, 3},
  {116, kDep116, 3},
};
static const int kNumDepRules = 54;
}  // namespace hypersaw
